FROM python:3.6

RUN echo "Asia/Taipei" > /etc/timezone \
 && rm /etc/localtime && dpkg-reconfigure -f noninteractive tzdata

ENV PYTHONPATH=/app

COPY requirements.txt /app/
RUN pip install --upgrade pip \
 && pip install wheel \
 && pip install -r /app/requirements.txt \
 && rm -rf ~/.cache/pip

COPY run_worker.py /app/
COPY app /app/app/

# Use docker execute command
# CMD ["python", "/app/run_worker.py"]
